### ISSUE TITLE
可以更新一下前端的代码吗 

### ISSUE THREAD

**Issue by jessUnb** [guriytan/airbox-vue#1]

**Comment by guriytan** [comment]
后端改动有点大，前端会慢慢更新。

**Comment by gjjsgjj** [comment]
好的 还有那个后端是不是把文件夹那一块功能删了呀 我从路由和model那边都没看到

**Comment by gjjsgjj** [comment]
Files.vue 有个bug res.file.forEach(item => { 应该改成res.files.forEach(item => {

**Comment by guriytan** [comment]
现在前后端的接口和显示基本都通了，还剩一些优化。folder的定义与file的定义有点重复，使用了type来控制fodler这种类型。
